[workspace]
authors = ["Starfallen <36763490+Starfallan@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "reduce_cloudfare_image"
platforms = ["win-64"]
version = "0.1.0"

[pypi-options]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
extra-index-urls = ["https://pypi.org/simple"]

[tasks]

[dependencies]
boto3 = ">=1.26.0"
tqdm = ">=4.64.0"
requests = ">=2.28.0"
tabulate = ">=0.9.0"
python = "3.12.*"
libavif = ">=1.3.0,<2"

[pypi-dependencies]
pillow = ">=11.3.0, <12"
